### ISSUE TITLE
Actualizar total de datos

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ckan-dgm#3]
13,169

@netosw

**Comment by vaquer** [comment]
Este issue no va aqui, ya que este repo es practicamente de deploy.

El repo del plugin ckan es este:

https://github.com/vaquer/ckanext-mxtheme

**Comment by vaquer** [comment]
Ya subi el fix a ese repo. Solo hay que actualizar el contenedor en prod.

**Comment by carlosmaya** [comment]
resuelto por opintel/ckanext-mxtheme#7cc31d31331645cf2e1f2b3f2e351a9e240b5526
