### ISSUE TITLE
Agregar íconos para formatos

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ckan-dgm#4]
* PDF
* XLSX

![ic-xlsx](https://cloud.githubusercontent.com/assets/2633527/17224317/15975d2a-54c6-11e6-9f6e-1326fee1c890.png)

![ic-pdf](https://cloud.githubusercontent.com/assets/2633527/17224321/18ee1162-54c6-11e6-8bc1-8e14cdbaaded.png)

**Comment by vaquer** [comment]
Ya estan los nuevos iconos en el tema.

https://github.com/opintel/ckanext-mxtheme/commit/7751bcf16c421dc5d4c0b611f0804e54dbc69ef3
